default:
  tags:
    - nowum

stages:
- build

build-docker:
  image: docker:dind
  services:
    - docker:dind
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -f Dockerfile  -t "$CI_REGISTRY_IMAGE/smartdso:latest" .
    - docker push $CI_REGISTRY_IMAGE/smartdso:latest