version: "3.9"
services:

          scenario_80_30_0:
            container_name: s8030_0
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_0
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_1:
            container_name: s8030_1
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_1
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_2:
            container_name: s8030_2
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_2
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_3:
            container_name: s8030_3
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_3
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_4:
            container_name: s8030_4
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_4
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_5:
            container_name: s8030_5
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_5
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_6:
            container_name: s8030_6
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_6
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_7:
            container_name: s8030_7
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_7
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_8:
            container_name: s8030_8
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_8
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_9:
            container_name: s8030_9
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_9
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_10:
            container_name: s8030_10
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_10
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_11:
            container_name: s8030_11
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_11
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_12:
            container_name: s8030_12
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_12
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_13:
            container_name: s8030_13
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_13
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_14:
            container_name: s8030_14
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_14
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_15:
            container_name: s8030_15
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_15
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_16:
            container_name: s8030_16
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_16
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_17:
            container_name: s8030_17
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_17
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_18:
            container_name: s8030_18
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_18
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_19:
            container_name: s8030_19
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_19
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_20:
            container_name: s8030_20
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_20
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_21:
            container_name: s8030_21
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_21
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_22:
            container_name: s8030_22
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_22
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_23:
            container_name: s8030_23
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_23
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_24:
            container_name: s8030_24
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_24
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_25:
            container_name: s8030_25
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_25
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_26:
            container_name: s8030_26
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_26
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_27:
            container_name: s8030_27
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_27
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_28:
            container_name: s8030_28
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_28
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        
          scenario_80_30_29:
            container_name: s8030_29
            image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
            build: .
            environment:
              EV_RATIO: 80
              MINIMUM_SOC: 30
              BASE_PRICE: 29
              LONDON_DATA: True
              START_DATE: 2022/01/01
              END_DATE: 2022/01/15
              SCENARIO_NAME: EV80LIMIT30L_29
              RESULT_PATH: EV80LIMIT30L
            volumes:
              - ./sim_result:/src/sim_result
        