version: "3.9"
services:

      scenario_50_30:
        container_name: s_50_30
        image: registry.git.fh-aachen.de/nowum-energy/projects/smartdso/smartdso:latest
        build: .
        environment:
          EV_RATIO: 50
          MINIMUM_SOC: 30
          LONDON_DATA: False
          START_DATE: 2022-02-01
          END_DATE: 2022-02-02
        volumes:
          - ./sim_result/50_30:/src/sim_result/
    
